package com.algorithm.leetcode;

/**
 * https://leetcode.com/problems/find-the-difference/Given two strings s and t
 * which consist of only lowercase letters.
 * String t is generated by random shuffling string s and
 * then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 */
public class P389_DiffChar {

    public char findTheDifference(String s, String t) {
        if(s == null || s.trim().length() == 0) {
            if(t != null && t.length() == 1) {
                return t.charAt(0);
            }
        }
        if(t == null || t.trim().length() == 0) {
            if(s != null && s.length() == 1) {
                return s.charAt(0);
            }
        }
        int str1 = s.charAt(0) - 0;
        int str2 = t.charAt(0) - 0;

        for(int i=1; i<s.length(); i++) {
            str1 = str1 ^ (s.charAt(i) - 0);
        }
        for(int i=1; i<t.length(); i++) {
            str2 = str2 ^ (t.charAt(i) - 0);
        }

        return (char) (str1 ^ str2);
    }

    public static void main(String[] args) {
        P389_DiffChar mainObject = new P389_DiffChar();
        String s = "a";
        String t = "";
        System.out.println(mainObject.findTheDifference(s,t));
    }
}
